name: oceandata
channels:
  - conda-forge
  - defaults
dependencies:
  - pydap
  - matplotlib
  - networkx
  - numpy
  - pandas
  - scipy
  - tqdm
  - watermark
  - python-wget
  - shapely
  - Cartopy
  - cmocean
  - xarray
  - dask
  - netcdf4
